insert into countries (country,code2,code3,id) VALUES ("Afghanistan", "AF","AFG",4);
insert into countries (country,code2,code3,id) VALUES ("Albania", "AL","ALB",8);
insert into countries (country,code2,code3,id) VALUES ("Algeria", "DZ","DZA",12);
insert into countries (country,code2,code3,id) VALUES ("American Samoa", "AS","ASM",16);
insert into countries (country,code2,code3,id) VALUES ("Andorra", "AD","AND",20);
insert into countries (country,code2,code3,id) VALUES ("Angola", "AO","AGO",24);
insert into countries (country,code2,code3,id) VALUES ("Anguilla", "AI","AIA",660);
insert into countries (country,code2,code3,id) VALUES ("Antarctica", "AQ","ATA",10);
insert into countries (country,code2,code3,id) VALUES ("Antigua and Barbuda", "AG","ATG",28);
insert into countries (country,code2,code3,id) VALUES ("Argentina", "AR","ARG",32);
insert into countries (country,code2,code3,id) VALUES ("Armenia", "AM","ARM",51);
insert into countries (country,code2,code3,id) VALUES ("Aruba", "AW","ABW",533);
insert into countries (country,code2,code3,id) VALUES ("Australia", "AU","AUS",36);
insert into countries (country,code2,code3,id) VALUES ("Austria", "AT","AUT",40);
insert into countries (country,code2,code3,id) VALUES ("Azerbaijan", "AZ","AZE",31);
insert into countries (country,code2,code3,id) VALUES ("Bahamas (the)", "BS","BHS",44);
insert into countries (country,code2,code3,id) VALUES ("Bahrain", "BH","BHR",48);
insert into countries (country,code2,code3,id) VALUES ("Bangladesh", "BD","BGD",50);
insert into countries (country,code2,code3,id) VALUES ("Barbados", "BB","BRB",52);
insert into countries (country,code2,code3,id) VALUES ("Belarus", "BY","BLR",112);
insert into countries (country,code2,code3,id) VALUES ("Belgium", "BE","BEL",56);
insert into countries (country,code2,code3,id) VALUES ("Belize", "BZ","BLZ",84);
insert into countries (country,code2,code3,id) VALUES ("Benin", "BJ","BEN",204);
insert into countries (country,code2,code3,id) VALUES ("Bermuda", "BM","BMU",60);
insert into countries (country,code2,code3,id) VALUES ("Bhutan", "BT","BTN",64);
insert into countries (country,code2,code3,id) VALUES ("Bolivia (Plurinational State of)", "BO","BOL",68);
insert into countries (country,code2,code3,id) VALUES ("Bonaire, Sint Eustatius and Saba", "BQ","BES",535);
insert into countries (country,code2,code3,id) VALUES ("Bosnia and Herzegovina", "BA","BIH",70);
insert into countries (country,code2,code3,id) VALUES ("Botswana", "BW","BWA",72);
insert into countries (country,code2,code3,id) VALUES ("Bouvet Island", "BV","BVT",74);
insert into countries (country,code2,code3,id) VALUES ("Brazil", "BR","BRA",76);
insert into countries (country,code2,code3,id) VALUES ("British Indian Ocean Territory (the)", "IO","IOT",86);
insert into countries (country,code2,code3,id) VALUES ("Brunei Darussalam", "BN","BRN",96);
insert into countries (country,code2,code3,id) VALUES ("Bulgaria", "BG","BGR",100);
insert into countries (country,code2,code3,id) VALUES ("Burkina Faso", "BF","BFA",854);
insert into countries (country,code2,code3,id) VALUES ("Burundi", "BI","BDI",108);
insert into countries (country,code2,code3,id) VALUES ("Cabo Verde", "CV","CPV",132);
insert into countries (country,code2,code3,id) VALUES ("Cambodia", "KH","KHM",116);
insert into countries (country,code2,code3,id) VALUES ("Cameroon", "CM","CMR",120);
insert into countries (country,code2,code3,id) VALUES ("Canada", "CA","CAN",124);
insert into countries (country,code2,code3,id) VALUES ("Cayman Islands (the)", "KY","CYM",136);
insert into countries (country,code2,code3,id) VALUES ("Central African Republic (the)", "CF","CAF",140);
insert into countries (country,code2,code3,id) VALUES ("Chad", "TD","TCD",148);
insert into countries (country,code2,code3,id) VALUES ("Chile", "CL","CHL",152);
insert into countries (country,code2,code3,id) VALUES ("China", "CN","CHN",156);
insert into countries (country,code2,code3,id) VALUES ("Christmas Island", "CX","CXR",162);
insert into countries (country,code2,code3,id) VALUES ("Cocos (Keeling) Islands (the)", "CC","CCK",166);
insert into countries (country,code2,code3,id) VALUES ("Colombia", "CO","COL",170);
insert into countries (country,code2,code3,id) VALUES ("Comoros (the)", "KM","COM",174);
insert into countries (country,code2,code3,id) VALUES ("Congo (the Democratic Republic of the)", "CD","COD",180);
insert into countries (country,code2,code3,id) VALUES ("Congo (the)", "CG","COG",178);
insert into countries (country,code2,code3,id) VALUES ("Cook Islands (the)", "CK","COK",184);
insert into countries (country,code2,code3,id) VALUES ("Costa Rica", "CR","CRI",188);
insert into countries (country,code2,code3,id) VALUES ("Croatia", "HR","HRV",191);
insert into countries (country,code2,code3,id) VALUES ("Cuba", "CU","CUB",192);
insert into countries (country,code2,code3,id) VALUES ("Curaçao", "CW","CUW",531);
insert into countries (country,code2,code3,id) VALUES ("Cyprus", "CY","CYP",196);
insert into countries (country,code2,code3,id) VALUES ("Czechia", "CZ","CZE",203);
insert into countries (country,code2,code3,id) VALUES ("Côte d'Ivoire", "CI","CIV",384);
insert into countries (country,code2,code3,id) VALUES ("Denmark", "DK","DNK",208);
insert into countries (country,code2,code3,id) VALUES ("Djibouti", "DJ","DJI",262);
insert into countries (country,code2,code3,id) VALUES ("Dominica", "DM","DMA",212);
insert into countries (country,code2,code3,id) VALUES ("Dominican Republic (the)", "DO","DOM",214);
insert into countries (country,code2,code3,id) VALUES ("Ecuador", "EC","ECU",218);
insert into countries (country,code2,code3,id) VALUES ("Egypt", "EG","EGY",818);
insert into countries (country,code2,code3,id) VALUES ("El Salvador", "SV","SLV",222);
insert into countries (country,code2,code3,id) VALUES ("Equatorial Guinea", "GQ","GNQ",226);
insert into countries (country,code2,code3,id) VALUES ("Eritrea", "ER","ERI",232);
insert into countries (country,code2,code3,id) VALUES ("Estonia", "EE","EST",233);
insert into countries (country,code2,code3,id) VALUES ("Eswatini", "SZ","SWZ",748);
insert into countries (country,code2,code3,id) VALUES ("Ethiopia", "ET","ETH",231);
insert into countries (country,code2,code3,id) VALUES ("Falkland Islands (the) [Malvinas]", "FK","FLK",238);
insert into countries (country,code2,code3,id) VALUES ("Faroe Islands (the)", "FO","FRO",234);
insert into countries (country,code2,code3,id) VALUES ("Fiji", "FJ","FJI",242);
insert into countries (country,code2,code3,id) VALUES ("Finland", "FI","FIN",246);
insert into countries (country,code2,code3,id) VALUES ("France", "FR","FRA",250);
insert into countries (country,code2,code3,id) VALUES ("French Guiana", "GF","GUF",254);
insert into countries (country,code2,code3,id) VALUES ("French Polynesia", "PF","PYF",258);
insert into countries (country,code2,code3,id) VALUES ("French Southern Territories (the)", "TF","ATF",260);
insert into countries (country,code2,code3,id) VALUES ("Gabon", "GA","GAB",266);
insert into countries (country,code2,code3,id) VALUES ("Gambia (the)", "GM","GMB",270);
insert into countries (country,code2,code3,id) VALUES ("Georgia", "GE","GEO",268);
insert into countries (country,code2,code3,id) VALUES ("Germany", "DE","DEU",276);
insert into countries (country,code2,code3,id) VALUES ("Ghana", "GH","GHA",288);
insert into countries (country,code2,code3,id) VALUES ("Gibraltar", "GI","GIB",292);
insert into countries (country,code2,code3,id) VALUES ("Greece", "GR","GRC",300);
insert into countries (country,code2,code3,id) VALUES ("Greenland", "GL","GRL",304);
insert into countries (country,code2,code3,id) VALUES ("Grenada", "GD","GRD",308);
insert into countries (country,code2,code3,id) VALUES ("Guadeloupe", "GP","GLP",312);
insert into countries (country,code2,code3,id) VALUES ("Guam", "GU","GUM",316);
insert into countries (country,code2,code3,id) VALUES ("Guatemala", "GT","GTM",320);
insert into countries (country,code2,code3,id) VALUES ("Guernsey", "GG","GGY",831);
insert into countries (country,code2,code3,id) VALUES ("Guinea", "GN","GIN",324);
insert into countries (country,code2,code3,id) VALUES ("Guinea-Bissau", "GW","GNB",624);
insert into countries (country,code2,code3,id) VALUES ("Guyana", "GY","GUY",328);
insert into countries (country,code2,code3,id) VALUES ("Haiti", "HT","HTI",332);
insert into countries (country,code2,code3,id) VALUES ("Heard Island and McDonald Islands", "HM","HMD",334);
insert into countries (country,code2,code3,id) VALUES ("Holy See (the)", "VA","VAT",336);
insert into countries (country,code2,code3,id) VALUES ("Honduras", "HN","HND",340);
insert into countries (country,code2,code3,id) VALUES ("Hong Kong", "HK","HKG",344);
insert into countries (country,code2,code3,id) VALUES ("Hungary", "HU","HUN",348);
insert into countries (country,code2,code3,id) VALUES ("Iceland", "IS","ISL",352);
insert into countries (country,code2,code3,id) VALUES ("India", "IN","IND",356);
insert into countries (country,code2,code3,id) VALUES ("Indonesia", "ID","IDN",360);
insert into countries (country,code2,code3,id) VALUES ("Iran (Islamic Republic of)", "IR","IRN",364);
insert into countries (country,code2,code3,id) VALUES ("Iraq", "IQ","IRQ",368);
insert into countries (country,code2,code3,id) VALUES ("Ireland", "IE","IRL",372);
insert into countries (country,code2,code3,id) VALUES ("Isle of Man", "IM","IMN",833);
insert into countries (country,code2,code3,id) VALUES ("Israel", "IL","ISR",376);
insert into countries (country,code2,code3,id) VALUES ("Italy", "IT","ITA",380);
insert into countries (country,code2,code3,id) VALUES ("Jamaica", "JM","JAM",388);
insert into countries (country,code2,code3,id) VALUES ("Japan", "JP","JPN",392);
insert into countries (country,code2,code3,id) VALUES ("Jersey", "JE","JEY",832);
insert into countries (country,code2,code3,id) VALUES ("Jordan", "JO","JOR",400);
insert into countries (country,code2,code3,id) VALUES ("Kazakhstan", "KZ","KAZ",398);
insert into countries (country,code2,code3,id) VALUES ("Kenya", "KE","KEN",404);
insert into countries (country,code2,code3,id) VALUES ("Kiribati", "KI","KIR",296);
insert into countries (country,code2,code3,id) VALUES ("Korea (the Democratic People's Republic of)", "KP","PRK",408);
insert into countries (country,code2,code3,id) VALUES ("Korea (the Republic of)", "KR","KOR",410);
insert into countries (country,code2,code3,id) VALUES ("Kuwait", "KW","KWT",414);
insert into countries (country,code2,code3,id) VALUES ("Kyrgyzstan", "KG","KGZ",417);
insert into countries (country,code2,code3,id) VALUES ("Lao People's Democratic Republic (the)", "LA","LAO",418);
insert into countries (country,code2,code3,id) VALUES ("Latvia", "LV","LVA",428);
insert into countries (country,code2,code3,id) VALUES ("Lebanon", "LB","LBN",422);
insert into countries (country,code2,code3,id) VALUES ("Lesotho", "LS","LSO",426);
insert into countries (country,code2,code3,id) VALUES ("Liberia", "LR","LBR",430);
insert into countries (country,code2,code3,id) VALUES ("Libya", "LY","LBY",434);
insert into countries (country,code2,code3,id) VALUES ("Liechtenstein", "LI","LIE",438);
insert into countries (country,code2,code3,id) VALUES ("Lithuania", "LT","LTU",440);
insert into countries (country,code2,code3,id) VALUES ("Luxembourg", "LU","LUX",442);
insert into countries (country,code2,code3,id) VALUES ("Macao", "MO","MAC",446);
insert into countries (country,code2,code3,id) VALUES ("Madagascar", "MG","MDG",450);
insert into countries (country,code2,code3,id) VALUES ("Malawi", "MW","MWI",454);
insert into countries (country,code2,code3,id) VALUES ("Malaysia", "MY","MYS",458);
insert into countries (country,code2,code3,id) VALUES ("Maldives", "MV","MDV",462);
insert into countries (country,code2,code3,id) VALUES ("Mali", "ML","MLI",466);
insert into countries (country,code2,code3,id) VALUES ("Malta", "MT","MLT",470);
insert into countries (country,code2,code3,id) VALUES ("Marshall Islands (the)", "MH","MHL",584);
insert into countries (country,code2,code3,id) VALUES ("Martinique", "MQ","MTQ",474);
insert into countries (country,code2,code3,id) VALUES ("Mauritania", "MR","MRT",478);
insert into countries (country,code2,code3,id) VALUES ("Mauritius", "MU","MUS",480);
insert into countries (country,code2,code3,id) VALUES ("Mayotte", "YT","MYT",175);
insert into countries (country,code2,code3,id) VALUES ("Mexico", "MX","MEX",484);
insert into countries (country,code2,code3,id) VALUES ("Micronesia (Federated States of)", "FM","FSM",583);
insert into countries (country,code2,code3,id) VALUES ("Moldova (the Republic of)", "MD","MDA",498);
insert into countries (country,code2,code3,id) VALUES ("Monaco", "MC","MCO",492);
insert into countries (country,code2,code3,id) VALUES ("Mongolia", "MN","MNG",496);
insert into countries (country,code2,code3,id) VALUES ("Montenegro", "ME","MNE",499);
insert into countries (country,code2,code3,id) VALUES ("Montserrat", "MS","MSR",500);
insert into countries (country,code2,code3,id) VALUES ("Morocco", "MA","MAR",504);
insert into countries (country,code2,code3,id) VALUES ("Mozambique", "MZ","MOZ",508);
insert into countries (country,code2,code3,id) VALUES ("Myanmar", "MM","MMR",104);
insert into countries (country,code2,code3,id) VALUES ("Namibia", "NA","NAM",516);
insert into countries (country,code2,code3,id) VALUES ("Nauru", "NR","NRU",520);
insert into countries (country,code2,code3,id) VALUES ("Nepal", "NP","NPL",524);
insert into countries (country,code2,code3,id) VALUES ("Netherlands (the)", "NL","NLD",528);
insert into countries (country,code2,code3,id) VALUES ("New Caledonia", "NC","NCL",540);
insert into countries (country,code2,code3,id) VALUES ("New Zealand", "NZ","NZL",554);
insert into countries (country,code2,code3,id) VALUES ("Nicaragua", "NI","NIC",558);
insert into countries (country,code2,code3,id) VALUES ("Niger (the)", "NE","NER",562);
insert into countries (country,code2,code3,id) VALUES ("Nigeria", "NG","NGA",566);
insert into countries (country,code2,code3,id) VALUES ("Niue", "NU","NIU",570);
insert into countries (country,code2,code3,id) VALUES ("Norfolk Island", "NF","NFK",574);
insert into countries (country,code2,code3,id) VALUES ("Northern Mariana Islands (the)", "MP","MNP",580);
insert into countries (country,code2,code3,id) VALUES ("Norway", "NO","NOR",578);
insert into countries (country,code2,code3,id) VALUES ("Oman", "OM","OMN",512);
insert into countries (country,code2,code3,id) VALUES ("Pakistan", "PK","PAK",586);
insert into countries (country,code2,code3,id) VALUES ("Palau", "PW","PLW",585);
insert into countries (country,code2,code3,id) VALUES ("Palestine, State of", "PS","PSE",275);
insert into countries (country,code2,code3,id) VALUES ("Panama", "PA","PAN",591);
insert into countries (country,code2,code3,id) VALUES ("Papua New Guinea", "PG","PNG",598);
insert into countries (country,code2,code3,id) VALUES ("Paraguay", "PY","PRY",600);
insert into countries (country,code2,code3,id) VALUES ("Peru", "PE","PER",604);
insert into countries (country,code2,code3,id) VALUES ("Philippines (the)", "PH","PHL",608);
insert into countries (country,code2,code3,id) VALUES ("Pitcairn", "PN","PCN",612);
insert into countries (country,code2,code3,id) VALUES ("Poland", "PL","POL",616);
insert into countries (country,code2,code3,id) VALUES ("Portugal", "PT","PRT",620);
insert into countries (country,code2,code3,id) VALUES ("Puerto Rico", "PR","PRI",630);
insert into countries (country,code2,code3,id) VALUES ("Qatar", "QA","QAT",634);
insert into countries (country,code2,code3,id) VALUES ("Republic of North Macedonia", "MK","MKD",807);
insert into countries (country,code2,code3,id) VALUES ("Romania", "RO","ROU",642);
insert into countries (country,code2,code3,id) VALUES ("Russian Federation (the)", "RU","RUS",643);
insert into countries (country,code2,code3,id) VALUES ("Rwanda", "RW","RWA",646);
insert into countries (country,code2,code3,id) VALUES ("Réunion", "RE","REU",638);
insert into countries (country,code2,code3,id) VALUES ("Saint Barthélemy", "BL","BLM",652);
insert into countries (country,code2,code3,id) VALUES ("Saint Helena, Ascension and Tristan da Cunha", "SH","SHN",654);
insert into countries (country,code2,code3,id) VALUES ("Saint Kitts and Nevis", "KN","KNA",659);
insert into countries (country,code2,code3,id) VALUES ("Saint Lucia", "LC","LCA",662);
insert into countries (country,code2,code3,id) VALUES ("Saint Martin (French part)", "MF","MAF",663);
insert into countries (country,code2,code3,id) VALUES ("Saint Pierre and Miquelon", "PM","SPM",666);
insert into countries (country,code2,code3,id) VALUES ("Saint Vincent and the Grenadines", "VC","VCT",670);
insert into countries (country,code2,code3,id) VALUES ("Samoa", "WS","WSM",882);
insert into countries (country,code2,code3,id) VALUES ("San Marino", "SM","SMR",674);
insert into countries (country,code2,code3,id) VALUES ("Sao Tome and Principe", "ST","STP",678);
insert into countries (country,code2,code3,id) VALUES ("Saudi Arabia", "SA","SAU",682);
insert into countries (country,code2,code3,id) VALUES ("Senegal", "SN","SEN",686);
insert into countries (country,code2,code3,id) VALUES ("Serbia", "RS","SRB",688);
insert into countries (country,code2,code3,id) VALUES ("Seychelles", "SC","SYC",690);
insert into countries (country,code2,code3,id) VALUES ("Sierra Leone", "SL","SLE",694);
insert into countries (country,code2,code3,id) VALUES ("Singapore", "SG","SGP",702);
insert into countries (country,code2,code3,id) VALUES ("Sint Maarten (Dutch part)", "SX","SXM",534);
insert into countries (country,code2,code3,id) VALUES ("Slovakia", "SK","SVK",703);
insert into countries (country,code2,code3,id) VALUES ("Slovenia", "SI","SVN",705);
insert into countries (country,code2,code3,id) VALUES ("Solomon Islands", "SB","SLB",90);
insert into countries (country,code2,code3,id) VALUES ("Somalia", "SO","SOM",706);
insert into countries (country,code2,code3,id) VALUES ("South Africa", "ZA","ZAF",710);
insert into countries (country,code2,code3,id) VALUES ("South Georgia and the South Sandwich Islands", "GS","SGS",239);
insert into countries (country,code2,code3,id) VALUES ("South Sudan", "SS","SSD",728);
insert into countries (country,code2,code3,id) VALUES ("Spain", "ES","ESP",724);
insert into countries (country,code2,code3,id) VALUES ("Sri Lanka", "LK","LKA",144);
insert into countries (country,code2,code3,id) VALUES ("Sudan (the)", "SD","SDN",729);
insert into countries (country,code2,code3,id) VALUES ("Suriname", "SR","SUR",740);
insert into countries (country,code2,code3,id) VALUES ("Svalbard and Jan Mayen", "SJ","SJM",744);
insert into countries (country,code2,code3,id) VALUES ("Sweden", "SE","SWE",752);
insert into countries (country,code2,code3,id) VALUES ("Switzerland", "CH","CHE",756);
insert into countries (country,code2,code3,id) VALUES ("Syrian Arab Republic", "SY","SYR",760);
insert into countries (country,code2,code3,id) VALUES ("Taiwan (Province of China)", "TW","TWN",158);
insert into countries (country,code2,code3,id) VALUES ("Tajikistan", "TJ","TJK",762);
insert into countries (country,code2,code3,id) VALUES ("Tanzania, United Republic of", "TZ","TZA",834);
insert into countries (country,code2,code3,id) VALUES ("Thailand", "TH","THA",764);
insert into countries (country,code2,code3,id) VALUES ("Timor-Leste", "TL","TLS",626);
insert into countries (country,code2,code3,id) VALUES ("Togo", "TG","TGO",768);
insert into countries (country,code2,code3,id) VALUES ("Tokelau", "TK","TKL",772);
insert into countries (country,code2,code3,id) VALUES ("Tonga", "TO","TON",776);
insert into countries (country,code2,code3,id) VALUES ("Trinidad and Tobago", "TT","TTO",780);
insert into countries (country,code2,code3,id) VALUES ("Tunisia", "TN","TUN",788);
insert into countries (country,code2,code3,id) VALUES ("Turkey", "TR","TUR",792);
insert into countries (country,code2,code3,id) VALUES ("Turkmenistan", "TM","TKM",795);
insert into countries (country,code2,code3,id) VALUES ("Turks and Caicos Islands (the)", "TC","TCA",796);
insert into countries (country,code2,code3,id) VALUES ("Tuvalu", "TV","TUV",798);
insert into countries (country,code2,code3,id) VALUES ("Uganda", "UG","UGA",800);
insert into countries (country,code2,code3,id) VALUES ("Ukraine", "UA","UKR",804);
insert into countries (country,code2,code3,id) VALUES ("United Arab Emirates (the)", "AE","ARE",784);
insert into countries (country,code2,code3,id) VALUES ("United Kingdom of Great Britain and Northern Ireland (the)", "GB","GBR",826);
insert into countries (country,code2,code3,id) VALUES ("United States Minor Outlying Islands (the)", "UM","UMI",581);
insert into countries (country,code2,code3,id) VALUES ("United States of America (the)", "US","USA",840);
insert into countries (country,code2,code3,id) VALUES ("Uruguay", "UY","URY",858);
insert into countries (country,code2,code3,id) VALUES ("Uzbekistan", "UZ","UZB",860);
insert into countries (country,code2,code3,id) VALUES ("Vanuatu", "VU","VUT",548);
insert into countries (country,code2,code3,id) VALUES ("Venezuela (Bolivarian Republic of)", "VE","VEN",862);
insert into countries (country,code2,code3,id) VALUES ("Viet Nam", "VN","VNM",704);
insert into countries (country,code2,code3,id) VALUES ("Virgin Islands (British)", "VG","VGB",92);
insert into countries (country,code2,code3,id) VALUES ("Virgin Islands (U.S.)", "VI","VIR",850);
insert into countries (country,code2,code3,id) VALUES ("Wallis and Futuna", "WF","WLF",876);
insert into countries (country,code2,code3,id) VALUES ("Western Sahara", "EH","ESH",732);
insert into countries (country,code2,code3,id) VALUES ("Yemen", "YE","YEM",887);
insert into countries (country,code2,code3,id) VALUES ("Zambia", "ZM","ZMB",894);
insert into countries (country,code2,code3,id) VALUES ("Zimbabwe", "ZW","ZWE",716);
insert into countries (country,code2,code3,id) VALUES ("Iland Islands", "AX","ALA",248);